CREATE DATABASE adjuster;

USE adjuster;

CREATE TABLE campaign (
  id INTEGER UNSIGNED,
  name VARCHAR(255),
  cpm DECIMAL(5,2),
  startDate DATE,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE creative (
  id INTEGER UNSIGNED,
  parent_id INTEGER UNSIGNED,
  clicks BIGINT UNSIGNED,
  views BIGINT UNSIGNED,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (parent_id) REFERENCES campaign (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;
